#ifndef __MOTION_MODEL_DATA_H__
#define __MOTION_MODEL_DATA_H__

//this file is generated by tflite2c.py

#include <stdint.h>
extern const unsigned char g_motion_model_data[];
extern const unsigned int g_motion_model_data_len;
extern const char* g_motion_model_classes[];
extern const unsigned int g_motion_model_classes_num;

#endif
