#ifndef __FOMO_MOBILENETV2_MODEL_DATA_H__
#define __FOMO_MOBILENETV2_MODEL_DATA_H__

//this file is generated by tflite2c.py

#include <stdint.h>
extern const unsigned char g_fomo_mobilenetv2_model_data[];
extern const unsigned int g_fomo_mobilenetv2_model_data_len;

#endif
