#ifndef __MOBILENETV2_MODEL_DATA_H__
#define __MOBILENETV2_MODEL_DATA_H__

//this file is generated by tflite2c.py

#include <stdint.h>

extern const unsigned char g_mobilenetv2_model_data[];
extern const char*         g_mobilenetv2_model_classes[];
extern const unsigned int  g_mobilenetv2_model_data_len;

#endif
